classes: {
  entity: {
    style: {
      fill: "#FFFFFF"
      stroke: "#0D0D0D"
      stroke-width: 1
      border-radius: 16
      shadow: false
      font-color: "#0D0D0D"
      font: mono
      font-size: 14
      bold: false
    }
  }
  accent: {
    style: {
      fill: "#EAF1FE"
      stroke: "#2E4780"
    }
  }
  muted: {
    style: {
      fill: "#EEEEEE"
      stroke: "#CCCCCC"
      font-color: "#929591"
    }
  }
  hot: {
    style: {
      fill: "#FFEDDE"
      stroke: "#CC6F47"
      font-color: "#804126"
    }
  }
  zone: {
    style: {
      fill: "#FFFFFF"
      stroke: "#0D0D0D"
      stroke-width: 1
      border-radius: 16
      shadow: false
      font-color: "#0D0D0D"
      bold: false
    }
  }
  flow: {
    style: {
      stroke: "#0D0D0D"
      stroke-width: 1
      border-radius: 5
      font: mono
      font-size: 12
      font-color: "#0D0D0D"
      italic: false
    }
    target-arrowhead.style.filled: false
  }
  secondary-connection: {
    style: {
      stroke: "#929591"
      stroke-dash: 2
    }
  }
}
